// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Coord.Migrations
{
    [DbContext(typeof(CoordContext))]
    [Migration("20200525123027_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("Coord.Models.Coordenado", b =>
                {
                    b.Property<int>("CoordenadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoordenadorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("CoordenadoId");

                    b.HasIndex("CoordenadorId");

                    b.ToTable("Coordenado");
                });

            modelBuilder.Entity("Coord.Models.Coordenador", b =>
                {
                    b.Property<int>("CoordenadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("CoordenadorId");

                    b.ToTable("Coordenador");
                });

            modelBuilder.Entity("Coord.Models.Coordenado", b =>
                {
                    b.HasOne("Coord.Models.Coordenador", "Coordenador")
                        .WithMany()
                        .HasForeignKey("CoordenadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
